// PRD §6 — Internal types for the per-stage MCDA engine.
//
// Templates declare:
//   - intake schema (zod) — F-02 form fields
//   - candidate set — discrete options the engine ranks
//   - criteria — what we score candidates against (with default weights)
//   - constraints — hard veto rules (Stage 2)
//
// Each stage transforms a typed input into a typed output. Orchestrator wires them.
//
// Re-exports the clarifier protocol so any consumer that imports from
// lib/engine/types.ts (the canonical engine-types entry point) sees the
// full type surface — including the typed clarifier protocol that voice /
// native / async surfaces will route through.

import type { z } from "zod";

export type {
  ClarifierKind,
  ClarifierBase,
  ClarifierSlider,
  ClarifierStepper,
  ClarifierRange,
  ClarifierChips,
  ClarifierWidget,
  ClarifierMeta,
  ClarifierSubmission,
  ClarifierEvent,
} from "./clarifier";
export {
  ClarifierWidgetSchema,
  emitClarifier,
  parseClarifierWidget,
} from "./clarifier";

// ---------------------------------------------------------------------------
// V2 Pain-path + Recommendation types
// ---------------------------------------------------------------------------

/**
 * Canonical pain-path identifiers for the V2 recommendation domain.
 * Mirrors PainPathIdSchema in shared/schema.ts.
 */
export type PainPathId =
  | "referrals"
  | "research"
  | "admin"
  | "capacity_growth"
  | "follow_up"
  | "custom";

/**
 * PainPath — alias for PainPathId.
 * Used by the E2 pain-path classifier and scoring modules.
 */
export type PainPath = PainPathId;

/**
 * Classification result from classifyPainPath().
 * Mirrors PainPathClassificationSchema in shared/schema.ts.
 */
export interface PainPathClassification {
  path: PainPathId;
  /** 0-1 confidence. Below 0.7 = ambiguous; clarifiers will be populated. */
  confidence: number;
  /** ClarifierChips widgets emitted when confidence < 0.7. */
  clarifiers?: import("./clarifier").ClarifierChips[];
}

/**
 * A candidate AI task produced by generateCandidateTasks().
 * Distinct from the V1 CandidateTask which carries a numeric score.
 */
export interface CandidateTaskExt {
  id: string;
  taskName: string;
  taskDescription: string;
  aiCapability: string;
  dataNeeded: string;
  guardrails: string;
  startingLevel: "prompt" | "checklist" | "skill" | "plugin" | "agent";
  source: "library" | "generated";
}

/** The 9 PRD scoring criteria IDs (§"Candidate Task Scoring"). */
export type ScoringCriterion =
  | "pain_severity"
  | "frequency"
  | "time_burden"
  | "business_impact"
  | "ai_fit"
  | "risk"
  | "data_readiness"
  | "adoption_friction"
  | "setup_effort";

/** Per-criterion score with rationale (method trace). */
export interface CriterionScore {
  raw: number;
  adjusted: number;
  rationale: string;
}

/** Scoring context from the user intake. */
export interface ScoringInput {
  painSeverity: number;
  frequency: number;
  timeBurden: number;
  riskTolerance: number;
  aiComfort: number;
  dataReadiness: number;
  weights?: Partial<Record<ScoringCriterion, number>>;
}

/** A scored + ranked candidate task. */
export interface ScoredCandidate extends CandidateTaskExt {
  scores: Record<ScoringCriterion, CriterionScore>;
  combinedScore: number;
  rank: number;
}

/**
 * Candidate task surfaced from the library or generated by the engine.
 */
export interface CandidateTask {
  id: string;
  title: string;
  description: string;
  painPath: PainPathId;
  /** 0-100 relevance score produced by Stage scoring. */
  score: number;
  tags: string[];
}

// ---------------------------------------------------------------------------
// Stage 8 — Adoption-pathway types
// ---------------------------------------------------------------------------

/** The five rung kinds available in the adoption pathway. */
export type AdoptionPathwayKind = "prompt" | "checklist" | "skill" | "plugin" | "agent";

/** Visibility state for a rung in the AdoptionPathwayPicker (U4). */
export type AdoptionPathwayState = "recommended" | "optional" | "not-recommended";

/**
 * Permission tier for builder-handoff seeds. Mirrors Stage 7 scaffold tiers.
 * T0 = paste-only, T1 = local install, T2 = plugin, T3 = agent.
 */
export type BuilderPermissionTier = "T0" | "T1" | "T2" | "T3";

/** Scaffold target for skill/plugin/agent seeds. */
export type BuilderScaffoldTarget = "claude-code-skill" | "claude-code-plugin";

/** Typed seed payload for the prompt builder bridge (U4). */
export interface PromptBuilderSeed {
  builderKind: "prompt";
  taskTitle: string;
  taskDescription: string | null;
  painPath: PainPathId;
  scoringRationale: string;
  targetAudience: string;
  outputSpec: string;
  permissionTier: "T0";
}

/** Typed seed payload for the checklist builder bridge (U4). */
export interface ChecklistBuilderSeed {
  builderKind: "checklist";
  taskTitle: string;
  taskDescription: string | null;
  painPath: PainPathId;
  scoringRationale: string;
  stepCountTarget: number;
  format: "ordered-steps";
  permissionTier: "T0";
}

/** Typed seed payload for the skill builder bridge (U4). */
export interface SkillBuilderSeed {
  builderKind: "skill";
  taskTitle: string;
  taskDescription: string | null;
  painPath: PainPathId;
  scoringRationale: string;
  scaffoldTarget: "claude-code-skill";
  permissionTier: "T1";
}

/** Typed seed payload for the plugin builder bridge (U4). */
export interface PluginBuilderSeed {
  builderKind: "plugin";
  taskTitle: string;
  taskDescription: string | null;
  painPath: PainPathId;
  scoringRationale: string;
  scaffoldTarget: "claude-code-plugin";
  permissionTier: "T2";
}

/** Typed seed payload for the agent builder bridge (U4). */
export interface AgentBuilderSeed {
  builderKind: "agent";
  taskTitle: string;
  taskDescription: string | null;
  painPath: PainPathId;
  scoringRationale: string;
  scaffoldTarget: "claude-code-plugin";
  permissionTier: "T3";
}

/** Discriminated union of all builder-handoff seeds. */
export type BuilderHandoffSeed =
  | PromptBuilderSeed
  | ChecklistBuilderSeed
  | SkillBuilderSeed
  | PluginBuilderSeed
  | AgentBuilderSeed;

/**
 * One rung in the adoption pathway.
 * The picker renders only rungs where state !== "not-recommended".
 */
export interface AdoptionPathwayRung {
  kind: AdoptionPathwayKind;
  /** Short action-oriented label (≤80 chars). */
  label: string;
  /** One-sentence rationale for this rung's state. */
  rationale: string;
  /** 0-100 confidence that this rung fits. */
  confidence: number;
  builderHandoff: {
    /** Typed payload the server-side builder bridge consumes (U4). Server-side only. */
    seed: BuilderHandoffSeed;
  };
  state: AdoptionPathwayState;
}

/**
 * Full adoption pathway: exactly 5 entries (one per kind: prompt, checklist,
 * skill, plugin, agent). Stage 8 sets this on every run.
 */
export type AdoptionPathway = [
  AdoptionPathwayRung, // prompt
  AdoptionPathwayRung, // checklist
  AdoptionPathwayRung, // skill
  AdoptionPathwayRung, // plugin
  AdoptionPathwayRung, // agent
];

// ---------------------------------------------------------------------------
// AiTaskRecommendation — primary V2 output object
// ---------------------------------------------------------------------------

/**
 * The recommended approach type — how the practitioner will act on this task.
 * Mirrors RecommendationApproach in the architecture doc.
 */
export type RecommendationApproach =
  | "existing_tool"
  | "prompt"
  | "checklist"
  | "sop"
  | "skill"
  | "plugin"
  | "agent"
  | "human_only";

/**
 * A method-trace entry for the recommendation engine pipeline.
 * Analogous to MethodTraceEntry in DecisionOutput but for the V2 path.
 */
export interface RecommendationMethodTraceEntry {
  stage: "pain-classify" | "use-case-retrieval" | "candidate-gen" | "scoring" | "stage8-promotion";
  name: string;
  output: unknown;
}

/**
 * Primary output of the V2 recommendation engine (runRecommendation()).
 * Mirrors AiTaskRecommendationSchema in shared/schema.ts.
 */
export interface AiTaskRecommendation {
  selectedPainPath: PainPathId;
  challengeSummary: string;
  goal: string;
  candidateTasks: CandidateTask[];
  recommendedTask: string;
  recommendedApproach: RecommendationApproach;
  whyThisTask: string;
  starterSolution: string;
  guardrails: string[];
  tryThisWeek: string[];
  successMetric: string;
  adoptionPathway: AdoptionPathway;
  confidence: number;
  methodTrace: RecommendationMethodTraceEntry[];
}

/**
 * Input to runRecommendation().
 */
export interface RecommendationInput {
  painPath: PainPathId;
  /** Free-text challenge description from the intake. */
  challengeText: string;
  /** Desired outcome / goal from the intake. */
  goal?: string;
  /** User context forwarded for RLS (server overrides client-supplied). */
  userId?: string;
  tenantId?: string;
}

export type CriterionDirection = "max" | "min";

/** Criterion definition for a decision template (structural: id, label, direction, defaultWeight). */
export interface CriterionDef {
  id: string; // short slug
  label: string; // human-readable
  description: string; // 1-2 sentence explanation for the UI
  direction: CriterionDirection; // max = higher is better, min = lower is better
  defaultWeight: number; // 0..1, will be normalized
}

export interface Candidate {
  id: string;
  label: string; // user-facing name e.g. "Hire a part-time virtual assistant"
  description: string; // 1-2 sentence explanation
  // Score per criterion in [0, 1]. Provided by the template author for v1
  // (deterministic, transparent). v2 may LLM-derive these from intake.
  scores: Record<string, number>;
}

export type ConstraintKind = "veto" | "soft";
export type ConstraintOperator = ">" | "<" | ">=" | "<=" | "==" | "!=";

export interface Constraint {
  id: string;
  label: string; // "Cannot exceed budget"
  description: string;
  kind: ConstraintKind;
  // The constraint targets either a candidate's `scores[criterion]` OR an
  // intake field. v1 supports intake-field constraints with operator + threshold.
  intakeField?: string; // e.g. "monthlyBudgetUSD"
  operator?: ConstraintOperator;
  // Threshold is either a literal number or an intake-derived expression.
  // For simplicity v1 uses literals.
  threshold?: number;
  // Eliminate any candidate whose scores[<criterionId>] is below threshold.
  criterionId?: string;
  vetoCandidates?: string[]; // candidates to veto when this constraint trips
}

export interface DecisionTemplate {
  id: "capacity" | "pricing" | "admin-hire";
  label: string; // human-readable
  description: string; // 1-2 sentences
  // Zod schema for the intake form. Used by F-02 (form validation) AND
  // by the engine (Stage 1 extracts values from these fields).
  intakeSchema: z.ZodTypeAny;
  // Form metadata for UI rendering. ≤7 fields per A-07.
  fields: Array<{
    name: string;
    label: string;
    helper?: string;
    kind: "number" | "text" | "select" | "boolean";
    options?: Array<{ value: string; label: string }>;
    required?: boolean;
    min?: number;
    max?: number;
  }>;
  candidates: Candidate[];
  criteria: CriterionDef[];
  constraints: Constraint[];
}
