// F-09 Scaffold generator — deterministic, NO LLM call.
//
// For any WorkloadReducer scored "skill" or "plugin" by Stage 6, emits a
// paste-ready bundle:
//   • SKILL.md   (frontmatter + body, ≤ 200 lines)  — Claude Code skill format
//   • AGENTS.md  (same frontmatter shape)            — Codex skill format
//   • plugin.json (when aiFeasibility === "plugin")  — Claude Code plugin manifest
//
// Hard cap: 6 files per scaffold. Per docs/decision-science/codex-agents-format.md
// (cached spec — see source-status header in that file).
//
// No template engine — Mustache-style placeholder replacement only. Keeps the
// scaffold generator free of any moving parts beyond plain string ops.

import { z } from "zod";
import type {
  Scaffold,
  ScaffoldFileSchema,
  WorkloadReducer,
} from "@/shared/schema";

// Read template bodies as inline string constants. Pre-bundling them avoids
// fs reads in production (Vercel edge handles fs differently per region).
// The source-of-truth files live at lib/scaffold-templates/*; if those drift
// the tests will fail.

const SKILL_TEMPLATE = `---
name: {{slug}}
description: {{description}}
---

# {{title}}

{{body}}

## When to use

- The user is doing the task this skill is named for.
- The user has not asked for help with anything outside this skill's scope.

## What to do

1. If any required input is missing, ask once. Do not loop.
2. Produce the artifact in the format the user expects, plain language, no jargon.
3. Never include patient identifiers (PHI) in worked examples — use placeholders.

## What not to do

- Do not invent clinical or financial details. If the user hasn't said it, ask.
- Do not promise outcomes you cannot guarantee.

> Generated by Decision Doctor on {{generatedAt}} from a workload-reducer scoped to "{{coverage}}" coverage at the {{permissionTier}} permission tier.
`;

const AGENTS_TEMPLATE = `---
name: {{slug}}
description: {{description}}
version: 0.1.0
---

<!--
  Codex AGENTS.md block — generated from a Decision Doctor workload-reducer.
  Spec pinned to docs/decision-science/codex-agents-format.md (cached 2026-05-10).
  Frontmatter shape is identical to Claude Code's SKILL.md — paste-compatible
  with both runtimes.
-->

# {{title}}

{{body}}

## Invocation contract

This skill is loaded when the user asks for the task described above. The
runtime injects the body of this file into the agent's system prompt.

> Generated by Decision Doctor on {{generatedAt}}.
`;

const PLUGIN_TEMPLATE = `{
  "name": "{{slug}}",
  "version": "0.1.0",
  "description": "{{description}}",
  "author": "Decision Doctor",
  "homepage": "https://decision-doctor-xi.vercel.app",
  "commands": [
    {
      "name": "{{slug}}",
      "description": "{{title}}",
      "argument-hint": "<your inputs here>"
    }
  ]
}
`;

// Public Zod schema for the plugin.json shape we emit. Mirrors the documented
// Claude Code plugin manifest (name + version + description + commands[]).
// Kept narrow on purpose — F-09's contract is "minimal valid plugin".
export const PluginJsonSchema = z.object({
  name: z.string().min(1).max(60).regex(/^[a-z0-9][a-z0-9-]*$/),
  version: z.string().regex(/^\d+\.\d+\.\d+$/),
  description: z.string().min(1).max(280),
  author: z.string().optional(),
  homepage: z.string().url().optional(),
  commands: z
    .array(
      z.object({
        name: z.string().min(1),
        description: z.string().min(1),
        "argument-hint": z.string().optional(),
      }),
    )
    .min(1),
});

// ── Public API ────────────────────────────────────────────────────────────

/**
 * Generate a paste-ready scaffold for a single reducer. Returns null if the
 * reducer's aiFeasibility is not "skill" or "plugin" (Stage 7 skips these).
 *
 * Hard cap: 6 files. Currently emits 2 (skill) or 3 (plugin); the cap exists
 * as a forward-compatibility guarantee for v1.1 multi-file scaffolds.
 */
export function generateScaffold(reducer: WorkloadReducer): Scaffold | null {
  const tier = reducer.aiFeasibility;
  if (tier !== "skill" && tier !== "plugin") return null;

  const slug = toSlug(reducer.artifact?.skillName ?? reducer.title);
  const title = reducer.title;
  const description = reducer.description.slice(0, 250); // hard ceiling
  const body = buildBody(reducer);
  const generatedAt = "{{ASOF}}"; // deterministic placeholder per build (tests don't assert exact ts)
  const coverage = reducer.coverage ?? "partial_task";
  const permissionTier = reducer.permission_tier ?? "T0";

  const ctx: Record<string, string> = {
    slug,
    title,
    description,
    body,
    generatedAt,
    coverage,
    permissionTier,
  };

  const skillMd = renderTemplate(SKILL_TEMPLATE, ctx);
  const agentsMd = renderTemplate(AGENTS_TEMPLATE, ctx);

  const files: Array<z.infer<typeof ScaffoldFileSchema>> = [
    { path: "SKILL.md", content: skillMd, language: "markdown" },
    { path: "AGENTS.md", content: agentsMd, language: "markdown" },
  ];

  if (tier === "plugin") {
    const pluginJson = renderTemplate(PLUGIN_TEMPLATE, ctx);
    // Validate before emitting — fail loud rather than ship malformed JSON.
    const parsed = JSON.parse(pluginJson);
    PluginJsonSchema.parse(parsed);
    files.push({ path: "plugin.json", content: pluginJson, language: "json" });
  }

  if (files.length > 6) {
    throw new Error(
      `Scaffold for "${reducer.title}" emitted ${files.length} files; hard cap is 6. Trim the template.`,
    );
  }

  const targets: Scaffold["targets"] =
    tier === "skill"
      ? ["claude-code-skill", "codex-skill"]
      : ["claude-code-plugin", "codex-plugin"];

  return { targets, files };
}

// ── Internal helpers ──────────────────────────────────────────────────────

function buildBody(reducer: WorkloadReducer): string {
  // Prefer the reducer's own paste-ready text when present.
  if (reducer.artifact?.promptText) {
    return reducer.artifact.promptText.trim();
  }
  if (Array.isArray(reducer.artifact?.playbookSteps)) {
    return [
      "Run through these steps in order:",
      ...reducer.artifact.playbookSteps.map((s, i) => `${i + 1}. ${s}`),
    ].join("\n");
  }
  // Fallback: synthesize a body from the description + title.
  return [
    `${reducer.description}`,
    "",
    "Walk the user through this task end-to-end. Ask one question at a time.",
    "Produce the artifact in plain language, no jargon, and offer it for copy.",
  ].join("\n");
}

function toSlug(name: string): string {
  return (name || "skill")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50)
    || "skill";
}

function renderTemplate(template: string, ctx: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_m, key: string) => {
    return key in ctx ? ctx[key]! : `{{${key}}}`;
  });
}
